//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquesceTray.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiquesceTray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap backup {
            get {
                object obj = ResourceManager.GetObject("backup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Config {
            get {
                object obj = ResourceManager.GetObject("Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap drop {
            get {
                object obj = ResourceManager.GetObject("drop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap free_space {
            get {
                object obj = ResourceManager.GetObject("free_space", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Liquesce {
            get {
                object obj = ResourceManager.GetObject("Liquesce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon LiquesceIcon {
            get {
                object obj = ResourceManager.GetObject("LiquesceIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquesce service is Stopped.
        /// </summary>
        internal static string NotifyIconHandler_DoStatusCheck_Liquesce_service_is_Stopped {
            get {
                return ResourceManager.GetString("NotifyIconHandler_DoStatusCheck_Liquesce_service_is_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started @ {0}.
        /// </summary>
        internal static string NotifyIconHandler_DoStatusCheck_Started____0_ {
            get {
                return ResourceManager.GetString("NotifyIconHandler_DoStatusCheck_Started____0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application tray is starting.
        /// </summary>
        internal static string NotifyIconHandler_NotifyIconHandler_Application_tray_is_starting {
            get {
                return ResourceManager.GetString("NotifyIconHandler_NotifyIconHandler_Application_tray_is_starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Status.
        /// </summary>
        internal static string NotifyIconHandler_NotifyIconHandler_Service_Status {
            get {
                return ResourceManager.GetString("NotifyIconHandler_NotifyIconHandler_Service_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquesce State In Error.
        /// </summary>
        internal static string NotifyIconHandler_SetState_Liquesce_State_In_Error {
            get {
                return ResourceManager.GetString("NotifyIconHandler_SetState_Liquesce_State_In_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquesce State Running.
        /// </summary>
        internal static string NotifyIconHandler_SetState_Liquesce_State_Running {
            get {
                return ResourceManager.GetString("NotifyIconHandler_SetState_Liquesce_State_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquesce State Stopped.
        /// </summary>
        internal static string NotifyIconHandler_SetState_Liquesce_State_Stopped {
            get {
                return ResourceManager.GetString("NotifyIconHandler_SetState_Liquesce_State_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquesce State Unknown.
        /// </summary>
        internal static string NotifyIconHandler_SetState_Liquesce_State_Unknown {
            get {
                return ResourceManager.GetString("NotifyIconHandler_SetState_Liquesce_State_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquesce State Warning.
        /// </summary>
        internal static string NotifyIconHandler_SetState_Liquesce_State_Warning {
            get {
                return ResourceManager.GetString("NotifyIconHandler_SetState_Liquesce_State_Warning", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon OKIcon {
            get {
                object obj = ResourceManager.GetObject("OKIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is already running.
        /// </summary>
        internal static string Program_CheckAndRunSingleApp__is_already_running {
            get {
                return ResourceManager.GetString("Program_CheckAndRunSingleApp__is_already_running", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon StopIcon {
            get {
                object obj = ResourceManager.GetObject("StopIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
