//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquesceSvc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"+Od6c3mNYXx4Ix17s1b9iwV7zOHdmMLj7nx+38vjnE36r9YlxR0/cZ6ISo/rez7Czcc4kZw55r/wVYDjNE2vqrjr4/VzgvgW1AgXzvTpLHAfK80RY58QQta1qtXbGgqsTxYJmFHk5ikCd5QFBth1xcJlZ5w62yaScPmWc2ygm58vorqrrTcgq7DIBJpz+YRaQhSKBFdj4IW6ug0OoOyoRkZRaHVTK/BwY2VR4QKRc1eK786/05qM4ABiX3tRrCFb7Ag2G4KleZD0Z2tznzk3ux0gPmLiXU5Hc/T+MEkxiGeQyXnI3Oy40TBgRL6Lv9dJ/TRiYXc32SvrfMgLqcaX0Ks56SfHmBIFLLwwFHRMx2U0HZnESsz2Nid+gJ4ILZDaUatqwAdUaS78rk7eMI3ubXrvA+n5PP3Df1PMI2M0C1LVX/b+OXSdlaVqS9XmMWtBlIh6xJQwlxz8PeargFlltKLroGpVROZJK1z5V5nP48yaaV8rKSb6SPIaybpfPPBy+CEdl57EU5Eh0MGmoWgAtDUQ2ygmEswHR1CyNKT/P7gt9rZDfcjatucd6rpoeY73BphSUQDNZY6MUTYlikg37l5Ob8HTRpI/FYwzSMTzxri4EbYA3reY4p5qNE/GiCmXcsgDaKGhKvz1gYHIugek4dVAaTA0tSqxiuyQtbO6jEz+KpwerYVI+4ir+oay3L1as8n603jeRdXHho7Vq5DsjtsipCEM4f/iq9rKy9sXSUXkOyS66gFktsCYUGxOacfAOeCtXIuIMsjhM8QRZJc+3A==")]
        public string Salt {
            get {
                return ((string)(this["Salt"]));
            }
        }
    }
}
